import type { Client, Project, Task, Deal, Activity, AnalyticsData } from "./types";

export const clients: Client[] = [
  {
    id: "c1",
    name: "Sarah Chen",
    company: "Apex Digital",
    email: "sarah@apexdigital.io",
    phone: "+1 (415) 555-0192",
    avatar: "SC",
    status: "active",
    totalValue: 84500,
    projectCount: 4,
    location: "Сан-Франциско, CA",
    industry: "Технологии",
    joinedAt: "2023-03-12",
    lastContact: "2026-06-01",
    tags: ["Корпоратив", "SaaS"],
  },
  {
    id: "c2",
    name: "Marcus Rivera",
    company: "Momentum Labs",
    email: "m.rivera@momentumlabs.co",
    phone: "+1 (312) 555-0847",
    avatar: "MR",
    status: "active",
    totalValue: 62000,
    projectCount: 3,
    location: "Чикаго, IL",
    industry: "Финтех",
    joinedAt: "2023-07-22",
    lastContact: "2026-05-28",
    tags: ["Финтех", "Стартап"],
  },
  {
    id: "c3",
    name: "Priya Nair",
    company: "Bloom Creative",
    email: "priya@bloomcreative.studio",
    phone: "+1 (646) 555-0321",
    avatar: "PN",
    status: "active",
    totalValue: 38000,
    projectCount: 2,
    location: "Нью-Йорк, NY",
    industry: "Дизайн",
    joinedAt: "2024-01-08",
    lastContact: "2026-06-03",
    tags: ["Агентство", "Креатив"],
  },
  {
    id: "c4",
    name: "James Okafor",
    company: "Ironclad Systems",
    email: "james.o@ironcladys.com",
    phone: "+1 (512) 555-0765",
    avatar: "JO",
    status: "lead",
    totalValue: 0,
    projectCount: 0,
    location: "Остин, TX",
    industry: "Кибербезопасность",
    joinedAt: "2024-05-20",
    lastContact: "2026-06-04",
    tags: ["Корпоратив", "Безопасность"],
  },
  {
    id: "c5",
    name: "Elena Volkova",
    company: "NorthStar Retail",
    email: "e.volkova@northstarretail.com",
    phone: "+1 (206) 555-0234",
    avatar: "EV",
    status: "active",
    totalValue: 51200,
    projectCount: 2,
    location: "Сиэтл, WA",
    industry: "Ритейл",
    joinedAt: "2023-11-15",
    lastContact: "2026-05-30",
    tags: ["E-commerce", "Ритейл"],
  },
  {
    id: "c6",
    name: "David Park",
    company: "Helix Health",
    email: "dpark@helixhealth.med",
    phone: "+1 (858) 555-0918",
    avatar: "DP",
    status: "inactive",
    totalValue: 29000,
    projectCount: 1,
    location: "Сан-Диего, CA",
    industry: "Здравоохранение",
    joinedAt: "2023-05-10",
    lastContact: "2026-03-14",
    tags: ["Здравоохранение", "B2B"],
  },
  {
    id: "c7",
    name: "Amara Diallo",
    company: "SkyBridge Ventures",
    email: "amara@skybridgevc.com",
    phone: "+1 (404) 555-0577",
    avatar: "AD",
    status: "active",
    totalValue: 112000,
    projectCount: 5,
    location: "Атланта, GA",
    industry: "Венчурный капитал",
    joinedAt: "2022-09-03",
    lastContact: "2026-06-02",
    tags: ["ВК", "Корпоратив", "Стратегич."],
  },
  {
    id: "c8",
    name: "Tom Becker",
    company: "Grassroot Media",
    email: "tom@grassrootmedia.net",
    phone: "+1 (503) 555-0143",
    avatar: "TB",
    status: "churned",
    totalValue: 14500,
    projectCount: 1,
    location: "Портленд, OR",
    industry: "СМИ",
    joinedAt: "2023-02-28",
    lastContact: "2026-01-20",
    tags: ["МСБ", "Медиа"],
  },
];

export const projects: Project[] = [
  {
    id: "p1",
    name: "Система фирменного стиля",
    clientId: "c3",
    clientName: "Bloom Creative",
    status: "in_progress",
    progress: 68,
    budget: 18000,
    spent: 11200,
    dueDate: "2026-07-15",
    startDate: "2026-04-01",
    description: "Полный редизайн бренда: логотип, типографика, цветовая система и гайдлайны.",
    taskCount: 24,
    completedTasks: 16,
    team: ["PR", "AL"],
    tags: ["Брендинг", "Дизайн"],
  },
  {
    id: "p2",
    name: "Интеграция и автоматизация CRM",
    clientId: "c1",
    clientName: "Apex Digital",
    status: "in_progress",
    progress: 42,
    budget: 35000,
    spent: 14800,
    dueDate: "2026-08-30",
    startDate: "2026-05-01",
    description: "Интеграция Salesforce с внутренними инструментами и автоматизация рабочих процессов.",
    taskCount: 38,
    completedTasks: 16,
    team: ["SC", "MK", "JD"],
    tags: ["Интеграция", "SaaS"],
  },
  {
    id: "p3",
    name: "MVP мобильного приложения",
    clientId: "c2",
    clientName: "Momentum Labs",
    status: "planning",
    progress: 15,
    budget: 62000,
    spent: 5200,
    dueDate: "2026-10-01",
    startDate: "2026-06-01",
    description: "Мобильное приложение на React Native для финтех-платформы обработки платежей.",
    taskCount: 56,
    completedTasks: 8,
    team: ["MR", "AL", "SC"],
    tags: ["Мобайл", "Финтех"],
  },
  {
    id: "p4",
    name: "Редизайн платформы e-commerce",
    clientId: "c5",
    clientName: "NorthStar Retail",
    status: "review",
    progress: 89,
    budget: 48000,
    spent: 44100,
    dueDate: "2026-06-20",
    startDate: "2026-01-15",
    description: "Полный перезапуск витрины интернет-магазина на Next.js и Stripe.",
    taskCount: 71,
    completedTasks: 63,
    team: ["EV", "PR", "TK"],
    tags: ["E-commerce", "Веб"],
  },
  {
    id: "p5",
    name: "Аудит безопасности",
    clientId: "c6",
    clientName: "Helix Health",
    status: "completed",
    progress: 100,
    budget: 29000,
    spent: 27600,
    dueDate: "2026-04-30",
    startDate: "2026-02-01",
    description: "Аудит соответствия HIPAA и укрепление безопасности инфраструктуры.",
    taskCount: 44,
    completedTasks: 44,
    team: ["DP", "JO"],
    tags: ["Безопасность", "Комплаенс"],
  },
  {
    id: "p6",
    name: "Инвесторский дашборд",
    clientId: "c7",
    clientName: "SkyBridge Ventures",
    status: "in_progress",
    progress: 55,
    budget: 42000,
    spent: 22000,
    dueDate: "2026-09-15",
    startDate: "2026-04-20",
    description: "Дашборд инвестиционного портфеля в реальном времени с аналитикой и отчётностью.",
    taskCount: 32,
    completedTasks: 18,
    team: ["AD", "MK"],
    tags: ["Аналитика", "Дашборд"],
  },
];

export const tasks: Task[] = [
  {
    id: "t1",
    title: "Документация токенов дизайн-системы",
    description: "Задокументировать все токены дизайна для системы фирменного стиля",
    projectId: "p1",
    projectName: "Система фирменного стиля",
    clientName: "Bloom Creative",
    assignee: "Priya Nair",
    assigneeAvatar: "PN",
    status: "in_progress",
    priority: "high",
    dueDate: "2026-06-10",
    createdAt: "2026-05-28",
    tags: ["Дизайн", "Документация"],
  },
  {
    id: "t2",
    title: "Маппинг API-эндпоинтов Salesforce",
    description: "Описать все необходимые API-эндпоинты Salesforce для интеграции",
    projectId: "p2",
    projectName: "Интеграция CRM",
    clientName: "Apex Digital",
    assignee: "Sarah Chen",
    assigneeAvatar: "SC",
    status: "todo",
    priority: "urgent",
    dueDate: "2026-06-08",
    createdAt: "2026-06-01",
    tags: ["API", "Интеграция"],
  },
  {
    id: "t3",
    title: "Вайрфреймы платёжного процесса",
    description: "Создать вайрфреймы для потоков оплаты и подтверждения платежа",
    projectId: "p3",
    projectName: "MVP мобильного приложения",
    clientName: "Momentum Labs",
    assignee: "Marcus Rivera",
    assigneeAvatar: "MR",
    status: "in_progress",
    priority: "high",
    dueDate: "2026-06-12",
    createdAt: "2026-06-02",
    tags: ["UX", "Мобайл"],
  },
  {
    id: "t4",
    title: "Регрессионное тестирование — оформление заказа",
    description: "Полное регрессионное тестирование корзины и оформления заказа перед запуском",
    projectId: "p4",
    projectName: "Редизайн платформы e-commerce",
    clientName: "NorthStar Retail",
    assignee: "Elena Volkova",
    assigneeAvatar: "EV",
    status: "todo",
    priority: "urgent",
    dueDate: "2026-06-09",
    createdAt: "2026-06-04",
    tags: ["QA", "Тестирование"],
  },
  {
    id: "t5",
    title: "Графики аналитики портфеля",
    description: "Разработать визуализацию эффективности портфеля на Recharts",
    projectId: "p6",
    projectName: "Инвесторский дашборд",
    clientName: "SkyBridge Ventures",
    assignee: "Amara Diallo",
    assigneeAvatar: "AD",
    status: "in_progress",
    priority: "medium",
    dueDate: "2026-06-18",
    createdAt: "2026-05-30",
    tags: ["Графики", "Аналитика"],
  },
  {
    id: "t6",
    title: "Серия писем для онбординга",
    description: "Написать 5-частную drip-кампанию для онбординга новых пользователей",
    projectId: "p2",
    projectName: "Интеграция CRM",
    clientName: "Apex Digital",
    assignee: "Sarah Chen",
    assigneeAvatar: "SC",
    status: "todo",
    priority: "medium",
    dueDate: "2026-06-20",
    createdAt: "2026-06-03",
    tags: ["Email", "Маркетинг"],
  },
  {
    id: "t7",
    title: "Финальная передача логотипа",
    description: "Упаковать и передать финальные файлы логотипа во всех форматах",
    projectId: "p1",
    projectName: "Система фирменного стиля",
    clientName: "Bloom Creative",
    assignee: "Priya Nair",
    assigneeAvatar: "PN",
    status: "done",
    priority: "high",
    dueDate: "2026-05-30",
    createdAt: "2026-05-10",
    tags: ["Дизайн", "Сдача"],
  },
  {
    id: "t8",
    title: "Настройка CI/CD пайплайна",
    description: "Настроить GitHub Actions для деплоя на staging и production",
    projectId: "p4",
    projectName: "Редизайн платформы e-commerce",
    clientName: "NorthStar Retail",
    assignee: "Elena Volkova",
    assigneeAvatar: "EV",
    status: "done",
    priority: "high",
    dueDate: "2026-06-01",
    createdAt: "2026-05-20",
    tags: ["DevOps", "CI/CD"],
  },
  {
    id: "t9",
    title: "Настройка навигации React Native",
    description: "Настроить стек и вкладочную навигацию React Navigation v7",
    projectId: "p3",
    projectName: "MVP мобильного приложения",
    clientName: "Momentum Labs",
    assignee: "Marcus Rivera",
    assigneeAvatar: "MR",
    status: "done",
    priority: "medium",
    dueDate: "2026-06-05",
    createdAt: "2026-05-28",
    tags: ["Мобайл", "Настройка"],
  },
  {
    id: "t10",
    title: "Интеграция WebSocket для данных в реальном времени",
    description: "Подключить дашборд к потоку данных в реальном времени через WebSocket",
    projectId: "p6",
    projectName: "Инвесторский дашборд",
    clientName: "SkyBridge Ventures",
    assignee: "Amara Diallo",
    assigneeAvatar: "AD",
    status: "todo",
    priority: "high",
    dueDate: "2026-06-25",
    createdAt: "2026-06-04",
    tags: ["WebSocket", "Реалтайм"],
  },
];

export const deals: Deal[] = [
  {
    id: "d1",
    title: "Корпоративная лицензия — Ironclad Systems",
    clientName: "James Okafor",
    clientAvatar: "JO",
    stage: "qualified",
    value: 85000,
    probability: 40,
    expectedClose: "2026-08-15",
    owner: "Amara Diallo",
  },
  {
    id: "d2",
    title: "Миграция платформы — Apex Digital",
    clientName: "Sarah Chen",
    clientAvatar: "SC",
    stage: "proposal",
    value: 42000,
    probability: 65,
    expectedClose: "2026-07-01",
    owner: "Marcus Rivera",
  },
  {
    id: "d3",
    title: "Аналитический пакет — SkyBridge Ventures",
    clientName: "Amara Diallo",
    clientAvatar: "AD",
    stage: "negotiation",
    value: 68000,
    probability: 80,
    expectedClose: "2026-06-30",
    owner: "Priya Nair",
  },
  {
    id: "d4",
    title: "Обновление бренда — NorthStar Retail",
    clientName: "Elena Volkova",
    clientAvatar: "EV",
    stage: "lead",
    value: 22000,
    probability: 20,
    expectedClose: "2026-09-01",
    owner: "Sarah Chen",
  },
  {
    id: "d5",
    title: "Инструменты комплаенса — Helix Health",
    clientName: "David Park",
    clientAvatar: "DP",
    stage: "closed_won",
    value: 29000,
    probability: 100,
    expectedClose: "2026-04-30",
    owner: "James Okafor",
  },
];

export const activities: Activity[] = [
  {
    id: "a1",
    type: "deal_won",
    title: "Сделка закрыта",
    description: "Инструменты комплаенса — Helix Health выиграна",
    timestamp: "2026-06-04T14:32:00Z",
    avatar: "DP",
    meta: "$29,000",
  },
  {
    id: "a2",
    type: "client_added",
    title: "Новый лид",
    description: "Добавлен лид: James Okafor из Ironclad Systems",
    timestamp: "2026-06-04T11:15:00Z",
    avatar: "JO",
  },
  {
    id: "a3",
    type: "task_done",
    title: "Задача выполнена",
    description: "Настройка CI/CD пайплайна — NorthStar Retail",
    timestamp: "2026-06-03T16:45:00Z",
    avatar: "EV",
  },
  {
    id: "a4",
    type: "project_created",
    title: "Проект начат",
    description: "MVP мобильного приложения запущен с Momentum Labs",
    timestamp: "2026-06-02T09:00:00Z",
    avatar: "MR",
    meta: "$62,000",
  },
  {
    id: "a5",
    type: "invoice",
    title: "Счёт отправлен",
    description: "Счёт №1042 отправлен Apex Digital",
    timestamp: "2026-06-01T10:00:00Z",
    avatar: "SC",
    meta: "$14,800",
  },
  {
    id: "a6",
    type: "task_done",
    title: "Задача выполнена",
    description: "Финальная передача логотипа — Bloom Creative",
    timestamp: "2026-05-30T15:20:00Z",
    avatar: "PN",
  },
  {
    id: "a7",
    type: "message",
    title: "Сообщение от клиента",
    description: "Amara Diallo запросила звонок с обновлением по статусу",
    timestamp: "2026-05-29T08:30:00Z",
    avatar: "AD",
  },
];

export const analyticsData: AnalyticsData = {
  revenue: [
    { month: "Янв", value: 28000, prev: 22000 },
    { month: "Фев", value: 34000, prev: 28000 },
    { month: "Мар", value: 31000, prev: 30000 },
    { month: "Апр", value: 46000, prev: 31000 },
    { month: "Май", value: 52000, prev: 46000 },
    { month: "Июн", value: 61000, prev: 52000 },
    { month: "Июл", value: 58000, prev: 58000 },
    { month: "Авг", value: 67000, prev: 58000 },
  ],
  clientGrowth: [
    { month: "Янв", value: 12 },
    { month: "Фев", value: 15 },
    { month: "Мар", value: 18 },
    { month: "Апр", value: 22 },
    { month: "Май", value: 26 },
    { month: "Июн", value: 31 },
    { month: "Июл", value: 35 },
    { month: "Авг", value: 38 },
  ],
  projectsByStatus: [
    { name: "В работе", value: 3, color: "#6366f1" },
    { name: "Планирование", value: 1, color: "#a78bfa" },
    { name: "Проверка", value: 1, color: "#f59e0b" },
    { name: "Завершён", value: 1, color: "#10b981" },
  ],
  taskCompletion: [
    { week: "Н1", completed: 18, total: 24 },
    { week: "Н2", completed: 22, total: 28 },
    { week: "Н3", completed: 15, total: 20 },
    { week: "Н4", completed: 27, total: 30 },
    { week: "Н5", completed: 31, total: 35 },
    { week: "Н6", completed: 24, total: 28 },
  ],
  topClients: [
    { name: "SkyBridge Ventures", value: 112000, change: 18.5 },
    { name: "Apex Digital", value: 84500, change: 12.3 },
    { name: "Momentum Labs", value: 62000, change: 34.7 },
    { name: "NorthStar Retail", value: 51200, change: -2.1 },
    { name: "Bloom Creative", value: 38000, change: 9.2 },
  ],
};

export const statsOverview = {
  totalRevenue: { value: 391700, change: 22.4 },
  activeClients: { value: 6, change: 2 },
  activeProjects: { value: 4, change: 1 },
  tasksDueToday: { value: 3, change: -1 },
  openDeals: { value: 3, change: 1 },
  pipelineValue: { value: 215000, change: 15.8 },
};
