/**
 * POST /api/integrations/telegram/webhook/[wsId]
 *
 * Workspace-scoped Telegram webhook receiver.
 * This is the canonical URL generated by getWebhookUrl(workspaceId).
 *
 * Security:
 *   - X-Telegram-Bot-Api-Secret-Token validated against the DB-stored value
 *     for this workspace using a constant-time HMAC comparison.
 *   - The raw bot token is never read or touched by this route.
 *   - Requests with missing or wrong secrets receive HTTP 401.
 *     Telegram does not retry 4xx responses.
 *
 * All parsing, validation, and persistence logic lives in
 * src/lib/telegram-webhook-handler.ts — shared with the legacy /webhook route.
 */

import { NextRequest, NextResponse } from "next/server";
import { handleWebhookUpdate }       from "@/lib/telegram-webhook-handler";

export async function POST(
  req:     NextRequest,
  context: { params: Promise<{ wsId: string }> },
): Promise<NextResponse> {
  const { wsId } = await context.params;
  return handleWebhookUpdate(wsId, req);
}
